### ISSUE TITLE
[DOCS] [WEBSITE] Grouping the adequate colors to a specific color scheme

### ISSUE THREAD

**Issue by Emcho0** [yorumicolors/yorumi#6]
It would be very helpful to provide a section before the color name and introduction to the color groups in the github README repo (and in website soon) to have a group of colors that match a scheme.

A good reference is the [Catppuccin palette](https://catppuccin.com/palette/) which has unfirom naming across the variants.

Mini example for Yorumi Abyss (to be later improvized once the changes in palette are finalized)

Quote from @esskayesss
> meanwhile we're upgrading and bringing about some minor changes to the palette, and adding more flavors to the theme.

```yaml
# Base colors for the colorscheme
yoruBg: "#060914"
yoruFg: "#BDBFCB"
# Dark highlights
yoruDarkYellow: "#9D672F"
yoruDarkMagenta: "#8D3F5A"
yoruDarkCyan: "#478584"
yoruDarkViolet: "#614686"
yoruDarkOrange: "#A06A2C"
# Light Highlights would be similarly grouped in this snippet above.
yoruLightYellow: "#E1C084"
yoruLightMagenta: "#E184AF"
yoruLightCyan: "#85E0CB"
yoruLightViolet: "#AD8FD6"
yoruLightOrange: "#F8A26D"
```

Why this is useful:
- Makes it easier for port maintainers to understand and apply the color scheme
- Simplifies the process of adding or updating colors
- Improves overall readability and structure for contributors and users
